---
# Override file for local testing with config from the default env var

version: "3.8"
services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints:latest-amd64
    volumes:
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
    environment:
      ECS_LOCAL_METADATA_PORT: "51679"
      HOME: "/home"
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-eu-west-1}
      AWS_PROFILE: ${AWS_PROFILE:-default}
    ports:
      - 51679:51679
    container_name: ecs-local-endpoints

  files-sidecar:
    container_name: files-sidecar
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3/containers/files-sidecar
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-eu-west-1}
      context: plain
      ECS_CONFIG_CONTENT: |

        files:
          /opt/files/test.txt:
            content: >-
              test from a yaml raw content
            owner: john
            group: root
            mode: 600
          /opt/files/aws.template:
            source:
              S3:
                BucketName: ${BUCKET_NAME:-sacrificial-lamb}
                Key: aws.yml

          /opt/files/ssm.txt:
            source:
              Ssm:
                ParameterName: /cicd/shared/kms/arn

          /opt/files/secret.txt:
            source:
              Secret:
                SecretId: GHToken

          /opt/files/test_ecs_property.txt:
            content: |
              {{ ecs_container_metadata('PrivateDNSName') }}
            context: jinja2

          /opt/files/test_ecs_properties.yaml:
            content: |
              {{ ecs_container_metadata() | to_yaml | safe }}
            context: jinja2
          /opt/files/test_ecs_properties.json:
            content: |
              {{ ecs_task_metadata() | to_json | safe }}
              # HELLO
              {{ ecs_container_metadata('ImageID')}}
            context: jinja2
            ignore_if_failed: true
            commands:
              post:
                - ls /opt/files
                - cat /opt/files/test_ecs_properties.json
                - chown 1000:1000 -R /opt/files
    depends_on:
      - ecs-local-endpoints

  confirm:
    image: public.ecr.aws/amazonlinux/amazonlinux:2
    container_name: testing
    volumes:
      - localshared:/opt/
    command:
      - ls
      - -l
      - /opt
    depends_on:
      - files-sidecar


volumes:
  localshared:
    driver: local
    driver_opts:
      device: /tmp/files
      o: bind
      type: none
