---
# Docker compose base

version: "3.8"

volumes:
  localshared:

services:
  files-sidecar:
    volumes:
      - localshared:/opt/files/
    image: public.ecr.aws/compose-x/ecs-files-composer:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    build:
      context: ./
