# generated by datamodel-codegen:
#   filename:  ecs-files-input.json
#   timestamp: 2023-08-20T15:14:27+00:00

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Union

S3Uri = str


ComposeXUri = str


class Encoding(Enum):
    base64 = "base64"
    plain = "plain"


class Context(Enum):
    plain = "plain"
    jinja2 = "jinja2"


@dataclass
class IgnoreFailureItem:
    commands: Optional[bool] = False
    mode: Optional[bool] = False
    owner: Optional[bool] = False
    source_download: Optional[bool] = False


@dataclass
class UrlDef:
    url: Optional[str] = None
    username: Optional[str] = None
    password: Optional[str] = None


@dataclass
class IamOverrideDef:
    role_arn: Optional[str] = None
    session_name: Optional[str] = "S3File@EcsConfigComposer"
    external_id: Optional[str] = None
    region_name: Optional[str] = None
    access_key_id: Optional[str] = None
    secret_access_key: Optional[str] = None
    session_token: Optional[str] = None


CommandsDef = List[str]


@dataclass
class X509CertDef:
    key_file_name: str
    cert_file_name: str
    dir_path: Optional[str] = None
    email_address: Optional[str] = "files-composer@compose-x.tld"
    common_name: Optional[str] = None
    country_name: Optional[str] = "ZZ"
    locality_name: Optional[str] = "Anywhere"
    state_or_province_name: Optional[str] = "Shire"
    organization_name: Optional[str] = "NoOne"
    organization_unit_name: Optional[str] = "Automation"
    validity_end_in_seconds: Optional[float] = 8035200
    group: Optional[str] = "root"
    owner: Optional[str] = "root"


@dataclass
class Certificates:
    x509: Optional[Dict[str, X509CertDef]] = None


@dataclass
class Commands:
    post: Optional[CommandsDef] = None
    pre: Optional[CommandsDef] = None


@dataclass
class SsmDef:
    parameter_name: Optional[str] = None
    iam_override: Optional[IamOverrideDef] = None


@dataclass
class SecretDef:
    secret_id: str
    version_id: Optional[str] = None
    version_stage: Optional[str] = None
    json_key: Optional[str] = None
    iam_override: Optional[IamOverrideDef] = None


@dataclass
class S3Def:
    s3_uri: Optional[S3Uri] = None
    compose_x_uri: Optional[ComposeXUri] = None
    bucket_name: Optional[str] = None
    bucket_region: Optional[str] = None
    key: Optional[str] = None
    iam_override: Optional[IamOverrideDef] = None


@dataclass
class SourceDef:
    url: Optional[UrlDef] = None
    ssm: Optional[SsmDef] = None
    s3: Optional[S3Def] = None
    secret: Optional[SecretDef] = None


@dataclass
class FileDef:
    path: Optional[str] = None
    content: Optional[str] = None
    source: Optional[SourceDef] = None
    encoding: Optional[Encoding] = "plain"
    group: Optional[str] = "root"
    owner: Optional[str] = "root"
    mode: Optional[str] = "0644"
    context: Optional[Context] = "plain"
    ignore_failure: Optional[Union[IgnoreFailureItem, bool]] = None
    commands: Optional[Commands] = None


@dataclass
class Model:
    files: Optional[Dict[str, FileDef]] = None
    certificates: Optional[Certificates] = None
    iam_override: Optional[IamOverrideDef] = None
